---
title: "Syllabus"
format: 
  html:
    toc: true
    link-external-newwindow: true
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
    self-contained: true
editor: source
---

## Classroom expectations {#classexpectations}

::: panel-tabset
### What you can expect from me

-   I will stay home if I am feeling sick and make arrangements to deliver the course material
-   I will work with you to arrange accommodations when you need them
-   I will respect your time by starting and ending class on time
-   I will answer your questions thoughtfully, and if I don't know the answer, I will follow up in a timely manner
-   I will embrace who you are as whole people
-   I will model respect, openness, and engagement, and foster a supportive and inclusive environment
-   I will be honest when I make mistakes, because failure is part of growing

### What I expect from you

-   That you will stay home if you are sick and contact me via email to arrange accommodations
-   That you genuinely attempt to engage with the course
-   That you ask questions if you are confused (you may do this privately -- there is no obligation to ask during class hours)
-   That you communicate with me when you have problems that interfere with your ability to engage with the coursework
-   That you treat your peers with respect and openness, and that you participate in creating an inclusive, supportive, and engaged classroom

### What is not expected
-   Perfection. Ever. It's a myth.
-   That you will 'sit still' or ask for permission to leave the classroom to go to the bathroom or if you just need a minute.
-   That everyone will learn in the same way. You do not have to match some "model student" to do well in this class
:::


## Team-Based Learning {#tbl}

I am using a variation of team-based learning for this class, in order to cultivate a community-minded classroom, encourage a growth mindset, and build group work skills. Here is how this will work:

We will have three modules, and you will work in a team of 4-5 students for each module. Your team will work on problems in class, discuss the content, and turn in a weekly problem that you solve together. At the end of each module, you will provide feedback on your teammates and on your own work, and then we will shuffle the groups, so you will have three different teams over the course of the semester.

In order to be a good member of your team, there will be a reading quiz and short warm-up problem (the PCQ) that must be completed prior to class. If you do not complete it prior to class, you must work alone to finish the assignment before you can join your team. I will take into account your attendance and whether you did the PCQs prior to class when assessing your community engagement for the module.

Not all of the work will be in groups. You will also have individual quizzes and homework.

I have tried to balance the class so that there is a mix of individual and group work, which I hope will allow everyone to get something meaningful out of the course.


## Assignments and Grading {#assignments}

Assignments fall into "bundles," which contribute to your grade equally. Your performance on each bundle determines your base grade (by averaging the grade in each bundle using the 4-point GPA scale). Beyond that, you can achieve grade boosts, which round your grade up, e.g. from a B to a B+, or a B+ to an A-.

You can learn more about each bundle below:

[Practice](#practice)

[Group Work](#groupwork)

[Quizzes](#quizzes)

[Excellence](#excellence)


### Grading Scheme {#gradingscheme}

### Table of letter grades

| Letter (pts)  | Practice                                              | Group Work                                                               | Quizzes            | Excellence  |
|---------------|-------------------------------------------------------| -------------------------------------------------------------------------|--------------------| ------------|
| D (1.0)       | Earn >= 60% average on WHWs, complete >= 60%  of PCQs | At least M on 6 Group Problems, at least M on 1 Community Engagement     | At least M on 4    | 0 Es        |  
| C (2.0)       | Earn >= 70% average on WHWs, complete >= 70%  of PCQs | At least M on 8 Group Problems, at least M on 2 Community Engagements    | At least M on 6    | 6 Es        |
| B (3.0)       | Earn >= 80% average on WHWs, complete >= 80%  of PCQs | At least M on 10 Group Problems, at least M on all Community Engagements | At least M on 8    | 12 Es       |
| A (4.0)       | Earn >= 90% average on WHWs, complete >= 90%  of PCQs | At least M on 12 Group Problems, at least M on all Community Engagements | At least M on 10   | 18 Es       |

: Letter grades {.striped .hover}

If, for example, you achieved an "C" in Practice, an "A" in Group Work, a "B" in Quizzes, and got a total of 7 "Es", your base grade would be (2.0 + 4.0 + 3.0 + 2.0)/4 = 2.75, which would be a B-. You could then get up to three grade round-ups.


### Grading scales

::: panel-tabset
#### Points and Completion
Homeworks will be graded on a points scale, and PCQs on whether you completed them (regardless of "correctness").

#### E/M/R/N {#emrn}
Quizzes, group problems, and community engagement are graded on this scale

- E: exceeds expectations
- M: meets expectations 
- R: revise / retry
- N: no submission 

E and M are considered passing grades. The number of Es you get will contribute to your overall grade (see the [grading scheme](#gradingscheme))

R and N are considered failing grades. 

In the case of quizzes and group problems, you will have one chance to revise/retry (see more under the assignment descriptions). Community engagement cannot be revised, as it is a reflection of your participation and engagement throughout the unit.

Under no circumstances can you revise something you receive an N on. Remember that done is better than perfect -- turn your work in so you can receive feedback.
:::


### Grading bundles

::: panel-tabset
#### Practice {#practice}

PCQs: In order to get the most out of class and be a good team member, you need to prepare. To do this, we will have daily reading and pre-class questions, which are google forms that ask you a few questions about the reading and ask you to work through a warm-up problem, which you must submit prior to class start. All I ask is that you show a good-faith effort to get full credit. You do not have to solve the warm-up problem correctly, and you will go over it with your group in class. 

*Given the purpose of the PCQs, I will not offer extensions or revisions, except in case of a major medical or family emergency that causes you to miss class.*

WHWs:  Regular problem-solving is very important to developing confidence and skill in this content, so every week you will have a short weekly problem set, which will be graded by a grader.

You may request extensions on the WHWs using the [extension form](https://forms.gle/eFx7y7FoSdoukKGC6).


#### Group Work {#groupwork}
Group Problems: Each week, your team will be responsible for completing and doing a formal write-up of one problem. You will submit one write-up together on Lyceum, which must be type-set and clearly organized. You may type-set using LaTeX/overleaf, Google docs, or any other word processing software that can handle mathematical expressions. For each part, make sure you include at least one sentence that describes the reasoning/explanation for the math you applied. This will be graded on correctness, thoroughness, and clarity, and will receive a grade of E, M, R, or N. Group problems receiving an R may be revised once.

You may request an extension as a group on these problems using the [extension form](https://forms.gle/eFx7y7FoSdoukKGC6).

Community Engagement: At the end of each module, you and your peers will fill out a form where you provide feedback on your teammates' contributions and your own. Your self-assessment and your peers' assessments will be weighted equally in the grade, and I will also take into account your participation in pre-class quizzes and your in-class attendance in order to determine a final grade for each module.

These are graded on an [E/M/R/N scale](#emrn). Not submitting your own form will result in an "N" regardless of how your team rates your participation.

I recognize that group work and peer grading can be fraught. I have been in many difficult group projects myself, and as a queer woman in physics, I'm very aware of cultural and social biases that exist in our field. If there are any concerning dynamics in your group, I hope that you feel safe talking to me in addition to including that information in your feedback form. You may also fill out my [anonymous feedback form](https://forms.gle/h1dzxVJKPEVo3v467) and give me only the information you think I need to address this issue anonymously.

#### Weekly quizzes {#quizzes}
There will be a closed-book quiz each week on Friday. These will mostly focus on recent content, but may sometimes require that you use skills from previous units.

If you have to miss class or leave early on a Friday due to an approved excuse, you may take the quiz at the testing center. You must do this no more than 2 days before the quiz is given and no more than 5 days after (i.e. starting the Wednesday before the quiz and ending the Wednesday after the quiz), and you can request this option through AESS using this [form](https://www.bates.edu/accessible-education-student-support/makeup-exam-requests/). If you are not sure your absence is excused or you feel you have a special circumstance, come and talk to me about it and we will discuss the options.

Quizzes are graded on an [E/M/R/N scale](#emrn). Each quiz will have a clear rubric of which learning objectives are being assessed and how to achieve an M or E on the quiz. There will be two opportunities to retake quizzes: once in the middle of the semester, and once during the "final exam" time slot (there is no final for this class)

#### Excellence {#excellence}
There are 25 potential "E" grades you can earn in this class: 10 quizzes, 12 group problems, and 3 community engagement grades. Every "E" you receive will be counted in this category and goes toward your final grade.

:::

### Grading boosts

Your base grade will be calculated from the table above, but you can round your grade up in a number of ways.

I will apply as many grade boosts as you achieve, with one exception:

You can only achieve an A+ in this class if you receive a base A grade. The A+ grade does not have an impact on your GPA, and so I am reserving it as a way of acknowledging especially excellent work across the course of the semester.

::: panel-tabset

#### Time Management 
If you use no more than 3 extension requests all semester (on individual assignments), I will round your grade up.

#### Growth 

If you demonstrate consistent improvement in your work across the semester, I reserve the right to round your grade up.

#### Metacognition 

In order to get this boost, you must do 5 of the following 7 assignments:

  -   Read an article on growth mindset and reflect on how it applies to your own life
  -   Fill out the first week of class form before the end of January
  -   Set a SMART goal (this will be evaluated on whether it meets the criteria) for a study skill to improve. You must do this before the end of January.
  -   Fill out the mid-semester survey before the end of February Recess
  -   Schedule an appointment with [a learning strategies tutor](https://www.bates.edu/student-academic-support-center/learning-strategies/) at SASC and write a reflection on one thing you learned at that meeting
  -   Bring questions to SASC at least once and write a reflection about your experience
  -   Come to my office hours at least once and write a reflection about your experience
  -   Reflect on your SMART goal at the end of the semester
  
  These assignments will all be posted in Lyceum under the "Metacognition" tab.
:::

## Deadlines and Extensions {#deadlines}
If you need an extension, you may request one using [this form](https://forms.gle/eFx7y7FoSdoukKGC6). I recognize that things come up and you may require flexibility at some point in the semester. Please feel free to reach out to me directly if you are struggling to meet a deadline. I want to support you and make sure you have the best possible chance for success in this class, and the only way I can help is if you communicate with me. Extension requests are always due before the deadline. Work submitted after the deadline without an approved extension will not be graded.

In general, I am happy to be flexible. Please note, however, that some assignments will have stricter deadlines, which are discussed in their descriptions above.


